### ISSUE TITLE
What should the output result be?

### ISSUE THREAD

**Issue by ngehani** [gaia-adm/docker-bench-test#2]
Successfully built cf6e933d699a
WARNING: Image for service docker-bench-test was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
bats: /var/docker-bench-test/tests/test_helper/bats-support/load.bash does not exist
/usr/local/libexec/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")

What is the expected result we should see? I ran:

`docker-compose run --rm docker-bench-test`

**Comment by alexei-led** [comment]
you suppose to find test results file under `/var/docker-bench-test/results`. Take a look at `Dockerfile`: default `ENTRYPOINT` and default `CMD`

**Comment by JoeReid** [comment]
I know this issue is old, however Google seems to like it when searching for BATS errors. Specifically `bats-support/load.bash does not exist`.

So for the benefit of anyone who finds themselves here hunting this issue down when using BATS as a git submodule, you may solve your problem by first running `git submodule init` then `git submodule update --recursive --remote`.
